### ISSUE TITLE
Feature Request - Space name in Menu Bar

### ISSUE THREAD

**Issue by JohnLockeNJ** [dado3212/spaces-renamer#68] opened 2020-09-16 16:20 UTC
It would be really great to have an option for the name of the current space to be displayed in the menu bar.

**Comment by dado3212** [comment] 2020-09-23 05:53
Duplicate of #5.

> Unfortunately Apple doesn't allow you to customize menu bar icons for different monitors, so this would break multi-monitor support.

**Closed by dado3212** 2020-09-23 05:53 UTC

**Comment by Flexperte** [comment] 2021-01-29 08:12
Maybe have two (or more) menu bar icons, one for each monitor? 
Either by running two separate instances, or by making a larger icon like SpaceID does. 

Would be really nice, between WhichSpace, SpaceID and Spaces-Renamer to have one utility that combines their features.
