### ISSUE TITLE
Desktop names not shown in expanded view

### ISSUE THREAD

**Issue by sorin-manole** [dado3212/spaces-renamer#82] opened 2022-02-28 07:46 UTC
The desktop name is shown only when hovering on it. Would it be possible to always show the deskopt name like we can see here?

https://github.com/dado3212/spaces-renamer/blob/master/largeView.jpg

**Comment by dado3212** [comment] 2022-03-05 04:20
The desktop name shows in the expanded view if you have below…I think 8? spaces. Above a certain number it only shows it when hovering. This is the same behavior as native, so not a change that SpacesRenamer introduces. It’s because displaying the name without hovering doesn’t have enough space to fit, so there’s no good UX to fix this. Marking as `wontfix`.

**Closed by dado3212** 2022-03-05 04:20 UTC

**Comment by sorin-manole** [comment] 2022-03-07 18:30
I understand. But based on your knowledge, would it be possible to change that?

**Comment by dado3212** [comment] 2022-03-24 05:36
Can you draw a picture of what the UI would look like? The issue is there's not enough space to put text of all of the names underneath.
