### ISSUE TITLE
Adding Display resets Desktop Names

### ISSUE THREAD

**Issue by newgoliath** [dado3212/spaces-renamer#15] opened 2018-04-16 12:56 UTC
Plugging in a Display-Port Display cable resets Desktop Names to default names, i.e.`desktop-1`, etc.  Configured names remain in spaces-renamer app.

Naming DP desktops with spaces-renamer app renames them on the laptop display, not the DP.  

Removing DP cable returns laptop-display desktop names to what was set already in spaces-renamer.

To make it work with DP plugged in:

- Quit Spacer-Renamer app
- `killall -9 Dock1
- mySimbl -> System Info -> Load into all applications
- start Spaces-Renamer app

**Comment by dado3212** [comment] 2018-04-16 16:58
This is due to a lack of clarity in OSX in some places about which monitor is which.  I have some possible ideas for a fix, I'll look into it later today and get back to you with a possible fix.

**Comment by ryanerwin** [comment] 2018-04-17 04:41
@dado3212 @newgoliath I'm having the exact same problem and I can confirm that it's like @dado3212  says, the space names are correct - but they're on the wrong monitor.

I think multi monitor support may be one of the reasons that this isn't included in Mac OS X... It's not completely obvious what to do with spaces and space names as you disconnect and reconnect displays.

1. 4K display connect to MBA... 5 named spaces on 4K display... 1 space on MBA _good_
2. Disconnect 4K display, 5 names spaces are now on MBA (but where did 1 space go?)
3. Reconnect 4K display, for OS X 5 spaces are back on 4K display (correct!) however Spaces Renamer shows those names on the MBA display...

Restart `spacesRenamer` then do `killall Dock` and things are back to normal.

**Comment by dado3212** [comment] 2018-04-18 06:35
It 100% could be included in actual OSX.  It's just my approach is unbelievably hacky, and involves just finding the text layer where it's rendered, and changing that name, as opposed to changing it in whatever model it's actually referred to as.

I pushed an update (v1.4.0), can you let me know if that clears up your problem?

**Comment by dado3212** [comment] 2018-04-24 17:01
Marking as solved.

**Closed by dado3212** 2018-04-24 17:01 UTC

**Comment by newgoliath** [comment] 2018-04-24 17:51
Works great!  Thanks!
