### ISSUE TITLE
Using Spaces Renamer with Monterey on M1 chip

### ISSUE THREAD

**Issue by paulsally** [dado3212/spaces-renamer#83] opened 2022-03-19 17:47 UTC
I installed MacForge and Spaces Renamer. I can rename the Spaces on Space Renamer but the names do not get reflected onto the Desktop names as shown pressing F3.

The names do get updated and remain persistent on SR:
![Screenshot 2022-03-19 at 18 32 13](https://user-images.githubusercontent.com/46979178/159132162-8df7c01a-9bb6-4590-af76-235d960eddf3.png)

I did disable System Integrity Protection:
![Screenshot 2022-03-19 at 18 39 47](https://user-images.githubusercontent.com/46979178/159132201-a976f25f-afaa-432d-86f1-7a5e77c40044.png)

The plugin shows in the Mac Forge's Manage Plugins tab:
<img width="552" alt="Screenshot 2022-03-19 at 18 29 48" src="https://user-images.githubusercontent.com/46979178/159132241-e92be55a-c15d-494d-9244-dfc04e24b05d.png">

It doesn't show, instead, in the Plugin Prefs and dragging and dropping the bundle there doesn't do anything:
<img width="552" alt="Screenshot 2022-03-19 at 18 29 48" src="https://user-images.githubusercontent.com/46979178/159132271-ffd41f4b-a8cc-497a-bfce-8b88bc62eb01.png">

**Versions**  
1. Mac Forge 1.1.0 - 
2. Spaces Renamer 1.9.1 -
3. MacOS version: 12.2.1 - 

I'm using a Macbook Pro with M1 chip. I've seen that there exist a beta version of Mac Forge that should be compatible with M1 chip but I don't know how to install it.

**Command Outputs**  
➜  ~ ps aux | grep -v grep | grep -i macforge
sara              1778   0.5  0.6 412905872  98016   ??  S     6:16PM   0:24.49 /Applications/MacForge.app/Contents/MacOS/MacForge
root              1826   0.0  0.0 34345988   1488   ??  Ss    6:16PM   0:00.23 /Library/PrivilegedHelperTools/com.macenhance.MacForge.Injector
sara              1805   0.0  0.2 409662288  28448   ??  S     6:16PM   0:00.91 /Applications/MacForge.app/Contents/Library/LoginItems/MacForgeHelper.app/Contents/MacOS/MacForgeHelper

➜  ~ ps aux | grep -v grep | grep -i spacesrenamer
sara              2599   0.0  0.1 35018392  20864   ??  S     6:19PM   0:06.19 /Applications/SpacesRenamer.app/Contents/MacOS/SpacesRenamer

➜  ~ csrutil status
System Integrity Protection status: disabled.

Thanks very much for your help.

.S.

**Comment by dado3212** [comment] 2022-03-24 05:35
Closing as a duplicate of #75, this has not been updated to work with M1 macs. I don't currently have an M1 test device, but am trying to track one down, that's likely the issue. Tagged the MacForge owner to see what the next step is.

**Closed by dado3212** 2022-03-24 05:35 UTC
